# Generated by Django 5.0.5 on 2024-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('leader_id', models.IntegerField()),
                ('meeting_name', models.CharField(max_length=100)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
            ],
        ),
    ]
