# Generated by Django 5.0.5 on 2024-05-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id_team', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=100)),
                ('id_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='CatchMe.user')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id_project', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pstart', models.DateField()),
                ('pend', models.DateField()),
                ('pdeadline', models.DateField()),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='CatchMe.team')),
            ],
        ),
        migrations.CreateModel(
            name='teamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='CatchMe.project')),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='CatchMe.team')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='CatchMe.user')),
            ],
        ),
    ]
