# Generated by Django 5.0.5 on 2024-05-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0002_team_project_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.user'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.project'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.user'),
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.user')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.project')),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.team')),
            ],
        ),
    ]
