# Generated by Django 5.0.5 on 2024-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0003_alter_project_id_team_alter_team_id_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pend',
            field=models.DateField(null=True),
        ),
    ]
