# Generated by Django 5.0.5 on 2024-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0004_alter_project_pend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pend',
            field=models.DateField(blank=True, null=True),
        ),
    ]
