# Generated by Django 5.0.5 on 2024-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0005_alter_project_pend'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(null=True),
        ),
    ]
