# Generated by Django 5.0.5 on 2024-05-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0006_meeting_meeting_date_meeting_meeting_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='awefae4t34', max_length=60),
        ),
    ]
