# Generated by Django 5.0.5 on 2024-05-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0007_alter_user_email'),
        ('CatchMe', '0007_user_password'),
    ]

    operations = [
    ]
