# Generated by Django 5.0.5 on 2024-05-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0008_merge_0007_alter_user_email_0007_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
