# Generated by Django 5.0.5 on 2024-05-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0008_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='set_password',
        ),
    ]
