# Generated by Django 5.0.5 on 2024-05-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0008_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
