# Generated by Django 5.0.5 on 2024-05-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0009_rename_password_user_set_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='set_password',
            new_name='password',
        ),
    ]
