# Generated by Django 5.0.5 on 2024-05-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0010_rename_set_password_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user12',
        ),
    ]
