# Generated by Django 5.0.5 on 2024-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0011_rename_user_user12'),
    ]

    operations = [
        migrations.AddField(
            model_name='user12',
            name='password2',
            field=models.CharField(default='34324jkshfkjs', max_length=60),
        ),
    ]
