# Generated by Django 5.0.5 on 2024-05-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0012_user12_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('password2', models.CharField(max_length=60)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.user'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatchMe.user'),
        ),
        migrations.DeleteModel(
            name='user12',
        ),
    ]
