# Generated by Django 5.0.5 on 2024-05-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatchMe', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
